name: MaSuitePortals
version: ${project.version}
main: fi.matiaspaavilainen.masuiteportals.bukkit.MaSuitePortals
depend: [WorldEdit, MaSuiteCore]
authors: [Masa]
api-version: 1.14
commands:
  setportal:
    description: Sets portal
    aliases: [createportal, portalset]
    permission: masuiteportals.portal.set
  delportal:
    description: Deletes portal
    aliases: [deleteportal, portaldel]
    permission: masuiteportals.portal.delete
  portals:
    description: List all available portals
    aliases: [portalslist, listportals]
    permission: masuiteportals.portal.list
